### ISSUE TITLE
not triggering Release job with github-tag-action@master

### ISSUE THREAD

**Issue by legnoh** [legnoh/hc-http-switch#2]
- https://github.com/legnoh/hc-http-switch/blob/master/.github/workflows/release.yml#L2
- https://developer.github.com/v3/git/refs/#create-a-reference
- https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
- https://github.com/anothrNick/github-tag-action/commit/b326202b0e07f855d96bbe0f0ce6b8f75b92bdf1#diff-b958f585a04af5ee2087610ea7180f34L50-R50

**Comment by legnoh** [comment]
bump時のGITHUB_TOKENにデフォルトのものを使わないことで回避できた。
```
- name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_LEGNOH }}
        DEFAULT_BUMP: patch
        WITH_V: true
```
